docker: support building architectures and parallel builds

diff --git a/pkgdata/molior-server/usr/lib/molior/build-docker b/pkgdata/molior-server/usr/lib/molior/build-docker
--- a/pkgdata/molior-server/usr/lib/molior/build-docker
+++ b/pkgdata/molior-server/usr/lib/molior/build-docker
@@ -72,6 +72,10 @@ echo
 
 log "APT Sources:"
 curl --max-time 30 -s "$MOLIOR_SERVER/api2/project/$PROJECT/$PROJECTVERSION/aptsources" > /etc/apt/sources.list
+if [ "$?" -ne 0 ]; then
+  echo "E: Error getting apt sources from $MOLIOR_SERVER/api2/project/$PROJECT/$PROJECTVERSION/aptsources" >&2
+  exit 1
+fi
 cat /etc/apt/sources.list | sed -e '/^#/d' -e '/^$/d' -e 's/^/ - /'
 
 echo
@@ -87,7 +91,7 @@ log " - $sources_url"
 pkgdir=`curl --max-time 30 -s $sources_url | /app/find-package-dir.pl $REPO_NAME $VERSION`
 if [ -z "$pkgdir" ]; then
   echo "E: Directory for source package $REPO_NAME $VERSION not found" >&2
-  exit 1
+  exit 2
 fi
 
 # strip epoch version
@@ -98,7 +102,7 @@ log " - $dsc_url"
 curl --max-time 30 -s -O $dsc_url
 if [ "$?" -ne 0 ]; then
   echo "E: Error downloading source package $dsc_url" >&2
-  exit 2
+  exit 3
 fi
 
 for srcfile in `/app/dsc-get-files.pl ${REPO_NAME}_$VERSION.dsc`
@@ -132,13 +136,13 @@ fi
 apt-get -y build-dep .
 if [ "$?" -ne 0 ]; then
   echo "E: Error installing build dependencies" >&2
-  exit 3
+  exit 4
 fi
 
-su build -c "dpkg-buildpackage -us -uc -ui -b"
+su build -c "dpkg-buildpackage -nc -us -uc -ui -b"
 if [ "$?" -ne 0 ]; then
   echo "E: Error building debian package $dsc_url" >&2
-  exit 4
+  exit 5
 fi
 
 if [ "$RUN_LINTIAN" = "True" ]; then
@@ -160,6 +164,6 @@ do
   curl -fs -F "file=@$f" $MOLIOR_SERVER/internal/buildupload/$BUILD_TOKEN >/dev/null
   if [ $? -ne 0 ]; then
     log_error "Error uploading output files"
-    exit 5
+    exit 6
   fi
 done
